---
- name: Create 
  hosts: localhost
  vars_files:
    - ./aws_vars.yml
    - group_vars/all.yml
    - group_vars/pass.yml
  gather_facts: false
  
  roles:
    # - { role: ec2-alb-loadbalancer-role, tags: ["ec2-alb"] }
    - { role: test-ec2-tg-role, tags: ["tg"] }
    # - { role: ec2-alb-role, tags: ["alb"] }
    